### ISSUE TITLE
LCD Pins

### ISSUE THREAD

**Issue by pmar146** [likeablob/macmini#10]
Hi There,
I notice on the LCD, you use pins 8,10 and 13. These are the backlight pins on the LCD. Where do these plug in on the OPI? I was looking at the pinout guide, but can't trace them there. 
Cheers and thanks

**Comment by likeablob** [comment]
@pmar146 Hi, in my case, these pins are connected as follows.

| LCD Pin                | Connected to                 |
| ---------------------- | ---------------------------- |
| 8 (GND)                | GND                          |
| 9, 10 (LED Anode)      | 3.3V (from OPi)                         |
| 11 (LED Cathode)       | NC (to prevent solder bridge) |
| 12,13,14 (LED Cathode) | GND (through 100 Ohm)        |
