### ISSUE TITLE
Cannot connect to vncserver :5901

### ISSUE THREAD

**Issue by pmar146** [likeablob/macmini#12]
Hi there and sorry to be a pest
I have done a clean install of Armbian Bionic and done a complete install of all the files on your page.

I seem to be able to boot up and get the big smiley Mac face on a white background  and a Mac arrow. Then I get an error:
Unable to connect to vnc server :5901. I then get sent back to the usual $ prompt

Is there something I have missed?

Regards
Pmar146

**Comment by likeablob** [comment]
@pmar146  Hi, no problem at all. My pleasure.

> I seem to be able to boot up and get the big smiley Mac face on a white background and a Mac arrow. Then I get an error:
> Unable to connect to vnc server :5901. I then get sent back to the usual $ prompt

Hmm, I'm not exactly sure what happened, but I guess `1_large_minimac.sh` through `3_basilisk.sh` might fail to be launched and the $ prompt you got was `4_terminal.sh`.
So could you paste what you get when you manually launch `1_large_minimac.sh` from that $ prompt?
```
$ ls ~/macmini/minivmac # All the required assets (e.g. ROM files) are installed correctly?
$ cd ~/macmini/switcher/sh.d
$ ./1_large_minimac.sh # Launch minivmac manually
```

**Comment by pmar146** [comment]
Hi Likeablob,
I tried to launch mini Mac manually and this brought up the big smiley face in the correct resolution. I have a working mouse, but there is nothing else. It feels. Like the Vancouver is loading but not minivmac,

I have checked that all the resources are in place and checked the .basilisk_ii_prefs points to the rom file and disk file correctly.

I am using my own Mac plus rom and my own .dsk file, renamed to your names.

I feel very close, but very far.

Best regards

________________________________

**Comment by likeablob** [comment]
@pmar146 
> the big smiley face

[This one, right?](https://github.com/likeablob/macmini/blob/master/images/macface.png) It's actually just a wallpaper. So that means minivmac has not been launched properly.  
What kind of output did you get from the terminal?  Let's debug the problem.

Also, could you try to launch `./6_clock.sh`?

> I feel very close, but very far.

I think we are almost there! :+1:

**Comment by pmar146** [comment]
Yes thats the one. I ran the commands from your last message and the one in this message from the terminal. This is what it said

macmini@orangepizeroplus2-h5:~$ ls ~/macmini/minivmac

minivmac.320                        minivmac.512

minivmac-3.5.8-larm-320x240.tar.gz  system.dsk

minivmac-3.5.8-larm-512x384.tar.gz  vMac.ROM

macmini@orangepizeroplus2-h5:~$ cd ~/macmini/switcher/sh.d

macmini@orangepizeroplus2-h5:~/macmini/switcher/sh.d$ ./1_large_minimac.sh

Killing Xtightvnc process ID 1843


New 'X' desktop is orangepizeroplus2-h5:1


Starting applications specified in /home/macmini/.vnc/xstartup

Log file is /home/macmini/.vnc/orangepizeroplus2-h5:1.log


Error: Can't open display:

./1_large_minimac.sh: line 9: ./minivmac.512: No such file or directory

macmini@orangepizeroplus2-h5:~/macmini/switcher/sh.d$ ls

1_large_minimac.sh  2_minimac.sh  3_basilisk.sh  4_terminal.sh  5_large_terminal.sh  6_clock.sh

macmini@orangepizeroplus2-h5:~/macmini/switcher/sh.d$ ./6_clock.sh

[2036:2036:0321/071126.045156:ERROR:browser_main_loop.cc(1512)] Unable to open X display.

macmini@orangepizeroplus2-h5:~/macmini/switcher/sh.d$

Does this mean the tar balls aren't installed correctly?
When I run ./6_clock.sh with the tv plugged into the HDMI port, after a bit of flashing, the TV shows a nice picture of water and the time. I think that is just a BIOS default in the Pi.

I hope this helps

________________________________

**Comment by likeablob** [comment]
@pmar146 
OK, it seems there are two different problems.
> Error: Can't open display:

For this one, to run the commands from SSH (not from the console on the LCD),  you have to export `DISPLAY=:0` env var to explicitly specify a Xorg instance to use.
```bash
$ export DISPLAY=:0
$ ./6_clock.sh # Then open http://simpleclock.surge.sh by using Chromium
```
<br/>

> ./1_large_minimac.sh: line 9: ./minivmac.512: No such file or directory

Second, I guess you have not replaced `minivmac/minivmac.{512,320}` with the binaries you compiled from the tarballs. You may want to have a try the following commands.
```bash
$ file ~/macmini/minivmac/minivmac.320 # Check the binary currently installed
***  ELF 32-bit LSB  shared object *** # If this output contains "32-bit", the binary is not for OPi H5.(64-bit)

$ cd path/to/extracted/minivmac-3.5.8-larm-320x240/
$ make # Just for sure
$ cp minivmac ~/macmini/minivmac/minivmac.320

$ cd path/to/extracted/minivmac-3.5.8-larm-512x384/
$ make # Just for sure
$ cp minivmac ~/macmini/minivmac/minivmac.512

$ cd ~/macmini/switcher/sh.d
$ export DISPLAY=:0 # If this happens in a SSH-ed console
$ ./1_large_minimac.sh
```

**Comment by likeablob** [comment]
@pmar146 
Additionally, I've added some pre-compiled 64-bit binaries to the `likeablob/feat-support-aarch64` branch.
However they were just built on Docker and I have not tested yet.   
I would be appreciate if you could try running them on your OPi H5.

```bash
$ cd ~/macmini
$ git fetch
$ git checkout likeablob/feat-support-aarch64 # Switch to the branch
$ ls minivmac/
... minivmac.aarch64.320 minivmac.aarch64.512 ...

$ cd ~/macmini/switcher/sh.d
$ ./1_large_minimac.sh 
```

**Comment by pmar146** [comment]
Hi Likeablob,
Thank you for persisting with this. The command from my ssh session looks like this:

macmini@orangepizeroplus2-h5:~/macmini/switcher/sh.d$ ./6_clock.sh
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
romium-browser/chromium-browser --type=gpu-process --field-trial-handle=3118818935237158989,16150629150991579119,131072 --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --shared-files: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
[1807:1840:0322/165922.948119:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1807:1840:0322/165923.338251:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[1807:1840:0322/165923.338445:ERROR:bus.cc(393)] Failed to connect to the bus: Could not parse server address: Unknown address type (examples of valid types are "tcp" and on UNIX "unix")
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
romium-browser/chromium-browser --type=gpu-process --field-trial-handle=3118818935237158989,16150629150991579119,131072 --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --shared-files: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
[1807:1875:0322/165923.861274:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1807:1875:0322/165923.863314:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[1807:1875:0322/165923.864832:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
romium-browser/chromium-browser --type=gpu-process --field-trial-handle=3118818935237158989,16150629150991579119,131072 --gpu-preferences=KAAAAAAAAAAgAAAgAAAAAAAAYAAAAAAAEAAAAAAAAAAAAAAAAAAAAAgAAAAAAAAA --shared-files: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
[1860:7:0322/165927.660184:ERROR:command_buffer_proxy_impl.cc(125)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[1860:1:0322/165929.579414:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.
[1860:1:0322/165929.580471:ERROR:child_process_sandbox_support_impl_linux.cc(79)] FontService unique font name matching request did not receive a response.


The second part checking the file with the binaries shows this:

file ~/macmini/minivmac/minivmac.320
/home/macmini/macmini/minivmac/minivmac.320: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.7.0, BuildID[sha1]=2a63282c317d6941014e1393878442ef928cd8ed, stripped

and
file ~/macmini/minivmac/minivmac.512
/home/macmini/macmini/minivmac/minivmac.512: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-, for GNU/Linux 3.7.0, BuildID[sha1]=2a63282c317d6941014e1393878442ef928cd8ed, stripped

I would love to test the new builds you have sent through. I have downloaded them and as soon as I can get my pi to do something useful, I'll be on to it. This is my minivmac directory as we speak.

macmini@orangepizeroplus2-h5:~/macmini/minivmac$ ls
aarch64.Dockerfile  docker-compose.yml  minivmac-3.5.8-larm                 minivmac-3.5.8-larm-512x384.tar.gz  minivmac.aarch64.320  minivmac.armv7l.320  README.md   vMac.ROM
armv7l.Dockerfile   minivmac.320        minivmac-3.5.8-larm-320x240.tar.gz  minivmac.512                        minivmac.aarch64.512  minivmac.armv7l.512  system.dsk

**Comment by pmar146** [comment]
If I try to ./1_large_minimac.sh in an ssh session I get this
./1_large_minimac.sh
Killing Xtightvnc process ID 1654
kill: (1654): No such process

New 'X' desktop is orangepizeroplus2-h5:1

Starting applications specified in /home/macmini/.vnc/xstartup
Log file is /home/macmini/.vnc/orangepizeroplus2-h5:1.log

./1_large_minimac.sh: line 10:  2173 Segmentation fault      ./minivmac.${ARCH}.512 system.dsk ${DISKS}
macmini@orangepizeroplus2-h5:~/macmini/switcher/sh.d$ 
Proto: RFB 003.008

Connected to RFB server, using protocol version 3.8

SelectSecurityType:
  sec-type[0]    2  (rfbSecTypeVncAuth)
  sec-type[1]   16  (rfbSecTypeTight)
Enabling TightVNC protocol extensions
Security-Type:  16  (rfbSecTypeTight)  Latency: 0.49 ms

Performing standard VNC authentication
VNC authentication succeeded

Desktop name "macmini's X desktop (orangepizeroplus2-h5:1)"

VNC server default format:
  32 bits per pixel.  Least significant byte first in each pixel.
  True colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
Warning: Cannot convert string "-*-helvetica-medium-r-*-*-12-*-*-*-*-*-*-*" to type FontStruct
Using default colormap which is TrueColor.  Pixel format:
  32 bits per pixel.  Least significant byte first in each pixel.
  True colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0
create_image()
create_image: created image_scale 512x384
create_image: scale: 320x240  0.6250 0.6250
try_create_image: shm image create fail: image == NULL
try_create_image: created *non-shm* image: 320x240
try_create_image: image->bytes_per_line: 1280
fs_supported: 1
size-A: 1024x768+0+0
size-B: 1024x768+0+0
size[0] 1024x768+0+0
size ok.
size-C: 1024x768+0+0

toplevel: 1024x768 viewport: 320x240
calling fs_grab()
calling XGrabKeyboard().
calling fs_ungrab()
calling XUngrabKeyboard(dpy)
size-A: 1024x768+0+0
size-B: 1024x768+0+0
size[0] 1024x768+0+0
size ok.
size-C: 1024x768+0+0

toplevel: 1024x768 viewport: 320x240
calling fs_grab()
calling XGrabKeyboard().

guessed: -compresslevel 1
guessed: -qualitylevel  9

Switching to faster ZRLE encoding in client-side scaling mode.
Switch back to Tight via the Popup menu if you prefer it.

prefer: ZRLE
Using default colormap which is TrueColor.  Pixel format:
  32 bits per pixel.  Least significant byte first in each pixel.
  True colour: max red 255 green 255 blue 255, shift red 16 green 8 blue 0

I am sorry but I am not much help. I should just get an H3

**Comment by likeablob** [comment]
@pmar146 

> ./1_large_minimac.sh: line 10: 2173 Segmentation fault ./minivmac.${ARCH}.512 system.dsk ${DISKS}

Oops. Thanks for the testing.   
Hmm, what would happen if you manually execute the binaries you compiled?

```bash
$ cd ~/macmini/minivmac
$ export DISPLAY=:0
$ vncserver -geometry 320x240 -depth 24
$ ssvncviewer -scale 1 :1 -fullscreen -passwd ~/.vnc/passwd 2>&1 > /dev/null &
$ export DISPLAY=:1
$ ./minivmac.320 system.dsk  # What will this output? 
```

**Comment by likeablob** [comment]
@pmar146 
Just a minute ago, I pushed newly compiled binaries to [likeablob/feat-support-aarch64](https://github.com/likeablob/macmini/tree/likeablob/feat-support-aarch64).

I'm almost sure the Seg. fault problem has gone, at least. 

```bash
$ cd ~/macmini
$ git pull
```
