### ISSUE TITLE
Resistor

### ISSUE THREAD

**Issue by pmar146** [likeablob/macmini#9]
The size of the resistor isn't clear in the image. Can you tell me what size you used?

**Comment by likeablob** [comment]
@pmar146 Hi,  I'm using a 100 ohm resistor. That is a current-limiting resistor to adjust screen brightness, so the optimum value may vary.

**Comment by pmar146** [comment]
Hi and thank your for the reply. I have printed the case and have a screen. Sadly my orange Pi is not the same as yours, so I am waiting on my new one to arrive. I love this little Mac. It is very cute.

________________________________

**Comment by likeablob** [comment]
My pleasure.Thank you for your feedback :+1: 
(I'd be happy if you could share the photos of your Mac.)

FYI, The Orange Pi used here is [`Orange Pi Zero +2 H3`](https://www.armbian.com/orange-pi-zero-plus-2-h3/). For `Orange Pi Zero +2 H5` (which has an arm64 CPU), you might need to recompile `minivmac`, at least.

**Comment by pmar146** [comment]
Hi there again,
I got my new OPi last week. Sadly they sent an H5 instead of H3. You mentioned I need to recompile minivmac. I have followed all your project on my Opi and I see you have 2 minivmacs in the minivmac folder. I haven’t tried to run them yet. I have just copied all my assets to the folder and that is where I stopped on your project on GitHub. I am not sure where to turn next. I haven’t connected my lcd yet. Just ssh through putty to get the job done so far.

I tried to upload pictures of my one, but  I can’t put them on github. Where is the best place to post them.

Cheers and best wishes

**Comment by likeablob** [comment]
@pmar146  Hi! Oops, I completely forgot to upload the source tarballs. Let me dig in my working dir...

Anyway, you can use the original author's [Mini vMac Variations Service](https://www.gryphel.com/c/minivmac/var_serv.html) to generate a tarball and follow [Build instruction](https://www.gryphel.com/c/minivmac/build.html) to compile it.

Also, even if pre-compiled `minivmac` doesn't run on your H5 OPiZero, the other shell scripts (apps) for example [sh.d/4_terminal.sh](https://github.com/likeablob/macmini/blob/master/switcher/sh.d/4_terminal.sh) probably work well. So you may see `xterm` launched once you've [correctly wired up the LCD and executed `install.sh`](https://github.com/likeablob/macmini#build-instruction). To debug these scripts, you might want to do as follows.

```bash
$ cd ~/macmini/switcher
$ npm start # Start `switcher` script manually
$ curl -v http://localhost:5501/ # Switch to a next script
or 
$ cd ~/macmini/switcher/sh.d
$ sh 4_terminal.sh # The other scripts can be executed in the same way.
```

(BTW, to upload pictures, try to drag&drop a file to GitHub's comment box.

**Comment by pmar146** [comment]
![IMG_6218](https://user-images.githubusercontent.com/59631663/75284472-9f3e8200-5860-11ea-9e1d-dab4f541df9f.JPG)
![IMG_6219](https://user-images.githubusercontent.com/59631663/75284486-a4033600-5860-11ea-93f0-22b696e060c7.JPG)
![IMG_6220](https://user-images.githubusercontent.com/59631663/75284490-a5346300-5860-11ea-88d1-605a08920853.JPG)
![IMG_6221](https://user-images.githubusercontent.com/59631663/75284491-a6659000-5860-11ea-89be-80173d536a02.JPG)

Here is my print of the case. I have been thoroughly enjoying this project.

**Comment by likeablob** [comment]
@pmar146 Hi, I've finally pushed [the tarballs to here](https://github.com/likeablob/macmini/tree/master/minivmac). 

Thank you. Nicely printed! (BTW, Have you printed `macintosh-mini-part-a.stl` (a upper part) upside down? That part can be printed w/o supports when it's rotated so that the -X(front) side is facing down.

**Comment by pmar146** [comment]
Hi likeablob
I haven't printed the part that way round. I might give it a go when I get the pi sorted out. Thank you for the compliments too. Incidentally, this was the first print I have done with supports, so I am happy with it.

Thank you for posting the tar balls. I am downloading now. 

I must compliment you on your soldering. This is not an easy thing to do on such a small ribbon cable.

Cheers and thanks

**Comment by pmar146** [comment]
Hi likeablob
I haven't printed the part that way round. I might give it a go when I get the pi sorted out. Thank you for the compliments too. Incidentally, this was the first print I have done with supports, so I am happy with it.

Thank you for posting the tar balls. I am downloading now. 

I must compliment you on your soldering. This is not an easy thing to do on such a small ribbon cable.

Cheers and thanks

**Comment by pmar146** [comment]
I tried make the tarball on the 320x240 and got the following error:
gcc "src/MINEM68K.c" -o "bld/MINEM68K.o" -c -Wall -Wmissing-prototypes -Wno-uninitialized -Wundef -Wstrict-prototypes -Os
gcc "src/OSGLUXWN.c" -o "bld/OSGLUXWN.o" -c -Wall -Wmissing-prototypes -Wno-uninitialized -Wundef -Wstrict-prototypes -Os
In file included from src/OSGLUXWN.c:38:0:
src/CNFGRAPI.h:16:10: fatal error: X11/Xlib.h: No such file or directory
 #include <X11/Xlib.h>
          ^~~~~~~~~~~~
compilation terminated.
Makefile:12: recipe for target 'bld/OSGLUXWN.o' failed
make: *** [bld/OSGLUXWN.o] Error 1

I am not sure what I did wrong there.

**Comment by likeablob** [comment]
@pmar146 Hi, In this case, try to install `libx11-dev` by `sudo apt install libx11-dev`. And if you face similar problems, try to google `${header name} ubuntu` (in this case `X11/Xlib.h ubuntu`) or  [use `apt-file` command to determine a package name](https://stackoverflow.com/a/33499131).
